FROM ubuntu

RUN \
    apt install -y \
        gnupg \
        software-properties-common \
    && wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import \
    && chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg \
    && add-apt-repository -y "deb https://qgis.org/ubuntu $(lsb_release -c -s) main" \
    && apt update \
    && apt install -y \
        qgis \
        qgis-plugin-grass

CMD ["/usr/bin/qgis"] 